services:

  Trendyol\ApiBundle\Client\ClientInterface:
    class: 'Trendyol\ApiBundle\Client\TrendyolClient'

  Trendyol\ApiBundle\Factories\UrlFactoryInterface:
    class: 'Trendyol\ApiBundle\Factories\TrendyolUrlFactory'

  Trendyol\ApiBundle\Services\:
    resource: '../../Services/*'
    autowire: true
    autoconfigure: true
    public: true

