trendyol_url:
  shipment_providers: "https://stageapi.trendyol.com/stagesapigw/shipment-providers"
  suppliers_addresses: "https://stageapi.trendyol.com/stagesapigw/suppliers/[sellerid]/addresses"
  category_list: "https://stageapi.trendyol.com/stagesapigw/product-categories"
  category_attributes: "https://stageapi.trendyol.com/stagesapigw/product-categories/[categoryid]/attributes"
  brand_list: "https://stageapi.trendyol.com/stagesapigw/brands"
  brand_by_name: "https://stageapi.trendyol.com/stagesapigw/brands/by-name"
  get_shipment_package: "https://stageapi.trendyol.com/stagesapigw/suppliers/[sellerid]/claims"
  create_claim: "https://stageapi.trendyol.com/stagesapigw/suppliers/[sellerid]/claims/create"
  approve_claim_line_items: "https://stageapi.trendyol.com/stagesapigw/claims/[claimid]/items/approve"
  create_claim_issue: "https://stageapi.trendyol.com/stagesapigw/claims/[claimid]/issue"
  get_claim_issue_reasons: "https://stageapi.trendyol.com/stagesapigw/claim-issue-reasons"
  create_common_label: "https://stageapi.trendyol.com/stagesapigw/suppliers/[sellerid]/common-label/[cargoTrackingNumber]"
  get_common_label: "https://stageapi.trendyol.com/stagesapigw/suppliers/[sellerid]/common-label/v2/[cargoTrackingNumber]"
  get_claim_audits: "https://stageapi.trendyol.com/integration/oms/core/sellers/[sellerid]/claims/items/[claimItemsid]/audit"
  shipment_packages: "https://stageapi.trendyol.com/stagesapigw/suppliers/[sellerid]/orders"
  update_tracking_id_number: "https://stageapi.trendyol.com/stagesapigw/suppliers/[sellerid]/[shipmentPackageid]/update-tracking-number"
  update_package: "https://stageapi.trendyol.com/stagesapigw/suppliers/[sellerid]/shipment-packages/[id]"
  send_invoice_link: "https://stageapi.trendyol.com/stagesapigw/suppliers/[sellerid]/supplier-invoice-links"
  split_multi_package_by_quantity: "https://stageapi.trendyol.com/stagesapigw/suppliers/[sellerid]/shipment-packages/[shipmentPackageid]/split-packages"
  split_shipment_package: "https://stageapi.trendyol.com/stagesapigw/suppliers/[sellerid]/shipment-packages/[shipmentPackageid]/split"
  multi_split_shipment_package: "https://stageapi.trendyol.com/stagesapigw/suppliers/[sellerid]/shipment-packages/[shipmentPackageid]/multi-split"
  split_shipment_package_by_quantity: "https://stageapi.trendyol.com/stagesapigw/suppliers/[sellerid]/shipment-packages/[shipmentPackageid]/quantity-split"
  update_box_info: "https://stageapi.trendyol.com/stagesapigw/suppliers/[sellerid]/shipment-packages/[shipmentPackageid]/box-info"
  update_package_un_supplied: "https://stageapi.trendyol.com/integration/oms/core/sellers/[sellerid]/shipment-packages/[shipmentPackageid]/items/unsupplied"
  product_create: "https://stageapi.trendyol.com/stagesapigw/suppliers/[sellerid]/v2/products"
  price_stock_update: "https://stageapi.trendyol.com/stagesapigw/suppliers/[sellerid]/products/price-and-inventory"
  product_listings: "https://stageapi.trendyol.com/stagesapigw/suppliers/[sellerid]/products"

